### ISSUE TITLE
行高计算问题

### ISSUE THREAD

**Issue by scofierd** [zhengwenming/WeChat#1]
当添加评论时，会出现其他cell的行高计算不准确，出现一大块空白 ，大神看下

**Comment by zhengwenming** [comment]
很感谢你的使用。
cell高度问题是commentId导致的，我用的是本地的测试数据，直接copy，有很多的commentId是一样的，没改过来，实际项目中每个评论的id是不一样的，这样缓存的高度都是根据id来的，如果id有重复，会导致bug，真实项目中不会出现。
另外我已经更新了，id都改为不一样的了，bug已经修复，请放心使用。

**Comment by scofierd** [comment]
@zhengwenming  这个commented 可以用indexPath.row进行代替的吧   （ps：这个demo用的很爽）

**Comment by zhengwenming** [comment]
可以，就是一个区别没个评论的id，没个评论都不一样，不可能存在一样的。

**Comment by JackWchen2015** [comment]
iOS 10 上，点击收起，展开，cell的高度没有变化

**Comment by zhengwenming** [comment]
点击收起，展开，cell的高度没有变化的bug已经修复，请更新最新demo
