### ISSUE TITLE
可以用SDAutoLayout做个适配版吗？或者讲解一下根据Cell高度计算Tableview高度的原理吗？

### ISSUE THREAD

**Issue by LittleLydia** [zhengwenming/WeChat#10]
因为项目其他部分用了SDAutoLayout布局方式，所以感觉再用mansory会稍微有点重复ing～但是用SDAutoLayout的时候，感觉计算的tableview的高度和cell的高度都有问题

**Comment by zhengwenming** [comment]
您好，我本人不用SDAutolayout的。
如果你用SDAutolayout，那么就没必要用我的demo了，SD已经提供了微信的demo，非常强大，很多人使用他来做朋友圈的布局，建议你直接去研究SD的微信demo。

**Comment by LittleLydia** [comment]
主要是GSD_WeiXin的评论不能点击，然后你的微信评论可以点击回复，所以我想着把你们结合起来用；在cell里嵌套一个UITableView我看到有些人都不支持这么干的，不过你还是这么干了，所以感觉很牛逼（赞）；不过有点小bug就是添加评论后点击 “全文／收起”时后面添加的评论不会显示出来ing。。。
听你的建议再次研究了下SD的微信，发现可以设置对评论进行回复的，希望后面不要有bug了ing～Anyway, thank you for sharing this and answering my question. ps:话说，平时画界面你们都用的Mansory嚒？～～

**Comment by zhengwenming** [comment]
对的，我xib+Mansory+代码frame布局，全都用。基本上现在界面都不是难题。就比如说，你让SD去搭建一个很复杂的界面，功能，会有问题吗。他对界面已经很熟悉了。所以，我建议你最好用一个比较熟悉的，第三方也可以，可以选择SDAutoLayout，或者mansonry都可以。用熟悉了，其实都一样。

**Comment by png666** [comment]
楼主代码是不是有问题啊，朋友圈不能评论啊

**Comment by LittleLydia** [comment]
@png666 可以评论呀；我运行起来可以评论，你看下你的代码
