### ISSUE TITLE
点击评论和点击回复评论没有反应

### ISSUE THREAD

**Issue by MansionWayh** [zhengwenming/WeChat#12]
重现：一次运行的时候，是可以正常的操作评论和回复评论点赞的，然后重新运行就没有反应了！！
![1](https://cloud.githubusercontent.com/assets/16216828/25223658/8d7a8ba6-25ee-11e7-941c-b1aecfbe1737.png)

System group container for systemgroup.com.apple.configurationprofiles path is /Users/bh/Library/Developer/CoreSimulator/Devices/013CB02A-0405-4271-B2C6-995A04D8298E/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
 WeChat[11672:2332424] [MC] Reading from private effective user settings.

**Comment by zhengwenming** [comment]
请真机测试
