### ISSUE TITLE
头像闪动

### ISSUE THREAD

**Issue by IsLandSea** [zhengwenming/WeChat#2]
展开全文的时候头像闪动了一下

**Comment by zhengwenming** [comment]
不是闪，是动画，系统自带的动画fade
如果你不想要这样的动画，可以修改枚举，改为UITableViewRowAnimationFade就可以了。具体代码如下

//更多
    cell.MoreBtnClickBlock = ^(UIButton *moreBtn,NSIndexPath * indexPath)
    {
        [weakSelf.chatKeyBoard keyboardDownForComment];
        weakSelf.chatKeyBoard.placeHolder = nil;
        model.isExpand = !model.isExpand;
        model.shouldUpdateCache = YES;
        [weakTable reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];//开发者可以随意选择自己喜欢的动画，也可以直接设置为无动画UITableViewRowAnimationNone
    };

**Comment by IsLandSea** [comment]
哦
