### ISSUE TITLE
第三方输入法导致键盘遮挡

### ISSUE THREAD

**Issue by heyehao2008** [zhengwenming/WeChat#3]
纯masonry写的朋友圈，不错。遇到几个问题：
1、使用系统的输入法没有问题。当使用搜狗输入法时。每次键盘弹起tableView滑动的位置都不准确。
2、第一次进入朋友圈这个界面的时候，滑不动或者说是滑动太卡，要过1~2秒才开始流畅滑动。这个是什么导致的呢
3、评论试使用tableView来做的，我也是用的cell嵌套tableView。但当某一条朋友圈的评论很多，比如50条，评论显示的范围超过一屏幕，此时这个评论tableView的cell貌似也不会重用。所以滑动到这一条朋友圈的时候，依然会感觉到一下卡帧。试了下微信，没有发现卡顿。也不知道微信的朋友圈是如何来布局的

**Comment by zhengwenming** [comment]
十分感谢你的反馈。
1、第三方键盘计算问题，我之前没测试，我手机没安装，后续会解决第三方键盘的问题。
2、刚进入页面卡顿，是因为加载了评论的键盘，键盘里面有很多资源，emoji和图片，比较耗内存，实际项目中可能不需要这个键盘，建议开发者自己写。
3、评论的cell多打50-100条的时候，评论cell是复用的。不存在不复用的问题。微信朋友圈里面的文字和图片是异步渲染到界面的，所以很流畅，后续我也会优化为异步的。

**Comment by zhengwenming** [comment]
你可以把键盘的懒加载代码注释掉，刚进来就不卡了，这里是一个键盘导致的，键盘的资源比较多。
具体代码如下：

-(ChatKeyBoard *)chatKeyBoard{
    if (_chatKeyBoard==nil) {
        _chatKeyBoard =[ChatKeyBoard keyBoardWithNavgationBarTranslucent:YES];
        _chatKeyBoard.delegate = self;
        _chatKeyBoard.dataSource = self;
        _chatKeyBoard.keyBoardStyle = KeyBoardStyleComment;
        _chatKeyBoard.allowVoice = NO;
        _chatKeyBoard.allowMore = NO;
        _chatKeyBoard.allowSwitchBar = NO;
        _chatKeyBoard.placeHolder = @"评论";
        [self.view addSubview:_chatKeyBoard];
        [self.view bringSubviewToFront:_chatKeyBoard];
    }
    return _chatKeyBoard;
}

**Comment by zhengwenming** [comment]
搜狗输入法的bug已经完美解决。
并添加了注释代码

**Comment by heyehao2008** [comment]
原来第三方输入法要三次调用通知。受教了。
针对第三个问题。我始终觉得评论的tableViewCell没有被复用。你项目里面在这个地方：
```objc
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    CommentCell *cell = [tableView dequeueReusableCellWithIdentifier:@"Cell"];
    if (!cell) {
        cell = [[CommentCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"Cell"];
        NSLog(@"创建cell");
    }else{
        NSLog(@"Cell 被复用了");
    }
    
    CommentModel *model = [self.messageModel.commentModelArray objectAtIndex:indexPath.row];
    [cell configCellWithModel:model];
    return cell;
}
```
我加入了打印创建cell。json数据里面，我把第一条动态的评论加到了50条。然后再次运行。刚刚进入朋友圈界面。就打印了几十行的创建cell。而一屏幕只能显示几条评论。
tableViewCell的重用是只创建屏幕上显示出来的cell个数。其他的从缓存队列里面去取。但这里的打印结果表示有几条评论就创建了几个cell

**Comment by zhengwenming** [comment]
大哥，是一个table吗？不是一个table，每个cell里面都还有table，是n个table！

**Comment by heyehao2008** [comment]
嗯，我知道是一个cell里面，评论的那块又是一个tableView。整个朋友圈是一个tableView。
项目中你命名为messageCell表示每一条动态。messageCell里面包含一个显示评论的tableView。这个tableView的cell为commentCell，表示某条动态的一条评论。
messageCell毋庸置疑是重用了的。我是说commentCell没有重用。

**Comment by zhengwenming** [comment]
最外面的大cell也是复用了的，也就是commentCell复用了。
这是tableViewCell的基本知识。这里就不讨论了。自己可以查看相关资料博客。
