### ISSUE TITLE
下下来第一次运行崩溃，还有就是伴随一堆autolayout的警告⚠️

### ISSUE THREAD

**Issue by LH-Liu** [zhengwenming/WeChat#6]
作者不看打印的嘛？

**Comment by zhengwenming** [comment]
你好，把崩溃信息贴出来，不然不能定位bug。
崩溃的原因太多了，具体要看崩溃信息。
至于autoLayout的警告⚠️问题，我是知道的，不会影响到项目，不会引起崩溃。这个是确定的，确定不会引起崩溃的。
