### ISSUE TITLE
行高计算是负数导致崩溃

### ISSUE THREAD

**Issue by HMsonghaibao** [zhengwenming/WeChat#7]
我用了您这个第三方来做类似朋友圈的应用,现在有个行高的问题,用那个缓存行高的框架,在ios9.3上没有问题,但在ios10上跑的时候,动态部分就会崩溃,说是行高计算结果是负数,但我把您的demo跑在ios10的手机是没有问题的,我不知道哪里有不同,麻烦指点一下

**Comment by zhengwenming** [comment]
有崩溃信息吗？如果方便的话，可以提供给我，谢谢。直接贴在这里就可以了。
