### ISSUE TITLE
内存泄露 ！ self.descLabel.attributedText = attrString;

### ISSUE THREAD

**Issue by dingfude2008** [zhengwenming/WeChat#9]
// 内存泄露
    self.descLabel.attributedText = attrString;

2016-12-16 12:01:38.219 WeChat[1627:952325] 循环引用个数:5 详细：{(
        (
        "-> CommentViewController ",
        "-> _tableView -> UITableView ",
        "-> _visibleCells -> __NSArrayM ",
        "-> MessageCell ",
        "-> _CommentBtnClickBlock -> __NSMallocBlock__ "
    ),
        (
        "-> _jggView -> JGGView ",
        "-> _tapBlock -> __NSMallocBlock__ ",
        "-> MessageCell "
    ),
        (
        "-> _jggView -> JGGView ",
        "-> _tapBlock -> __NSMallocBlock__ ",
        "-> MessageCell "
    ),
        (
        "-> CommentViewController ",
        "-> _tableView -> UITableView ",
        "-> _visibleCells -> __NSArrayM ",
        "-> MessageCell ",
        "-> _CommentBtnClickBlock -> __NSMallocBlock__ "
    ),
        (
        "-> CommentViewController ",
        "-> _tableView -> UITableView ",
        "-> _visibleCells -> __NSArrayM ",
        "-> MessageCell ",
        "-> _CommentBtnClickBlock -> __NSMallocBlock__ "
    )
)}

**Comment by zhengwenming** [comment]
怎么关闭了，是什么情况？
